@baseUrl = http://localhost:3000

### Get all users
GET {{baseUrl}}/api/users/all
Authorization: Bearer <token>

### Get single users
GET {{baseUrl}}/api/users
Authorization: Bearer <token>

### Add a new user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "Password123",
  "designation": "Developer",
  "task": 0,
  "ratings": 4
}

### update a user
PATCH {{baseUrl}}/api/users
Content-Type: application/json
Authorization: Bearer <token>

{
  "name": "John doe"
}

### authenticate user  (login)
### use the token from cookies and not from the res accessToken , refreshToken
POST {{baseUrl}}/api/auth
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "Password123"
}

### endpoint to get a new jwt token using the refresh token
POST {{baseUrl}}/api/auth/refresh-token
Cookie: refreshToken=<token>


### logout user
POST {{baseUrl}}/api/auth/logout
Content-Type: application/json

{}


### send message 
POST {{baseUrl}}/api/messages
Content-Type: application/json
Authorization: Bearer <token>

{
  "receiver": "receiver id",
  "content": "any reply ??"
}

### get all message by the user 
GET {{baseUrl}}/api/messages
Authorization: Bearer <token>

### get all message by the user and a single receiver
GET {{baseUrl}}/api/messages/:receiverId
Authorization: Bearer <token>

### with limits  start (start from what message) , limit (how many messages to get )
GET {{baseUrl}}/api/messages/<receiverId>?limit=2&start=0
Authorization: Bearer <token>